export const metadata = { title: "Privacy Policy — WhoopNess" };

export default function PrivacyPage() {
  return (
    <article className="prose-sm flex flex-col gap-3 text-sm leading-relaxed text-foreground-600">
      <h1 className="text-xl font-bold text-foreground">WhoopNess — Privacy Policy</h1>
      <p className="text-xs text-foreground-500">Last updated: 22 June 2026</p>

      <p>
        WhoopNess is a <b>private, single-user</b> application built and used by one individual for
        personal training guidance. It is <b>not affiliated with, endorsed by, or sponsored by
        WHOOP</b>. WHOOP is a trademark of WHOOP, Inc.
      </p>

      <h2 className="text-base font-semibold text-foreground">Data accessed</h2>
      <p>
        With your authorization via WHOOP OAuth, the app reads your own WHOOP data (recovery, sleep,
        workouts, cycles, profile, body measurements). It also stores training logs, preferences, and
        health information you provide.
      </p>

      <h2 className="text-base font-semibold text-foreground">How it&apos;s used</h2>
      <p>Solely to generate your personalized training and recovery guidance within the app.</p>

      <h2 className="text-base font-semibold text-foreground">Storage &amp; security</h2>
      <p>
        Data is stored in a private database accessible only to you, encrypted in transit and at
        rest. WHOOP access tokens are stored encrypted. Coaching text is generated by an AI provider
        (Anthropic) using only de-identified data.
      </p>

      <h2 className="text-base font-semibold text-foreground">Sharing</h2>
      <p>Your data is never sold or shared with third parties.</p>

      <h2 className="text-base font-semibold text-foreground">Retention &amp; deletion</h2>
      <p>You can revoke WHOOP access and request deletion of all stored data at any time.</p>

      <h2 className="text-base font-semibold text-foreground">Contact</h2>
      <p>nissimguez2@gmail.com</p>
    </article>
  );
}
